### ISSUE TITLE
Update instructions to use sam build

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/cookiecutter-aws-sam-python#24]
`sam build` is a new command that eases build source code to the format expected by the Lambda runtime. 

This issue is to reflect the work involved in doing so and whether it's sufficient to replace the experimental Makefile altogether.

**Comment by heitorlessa** [comment]
## Discovery

**`sam build`** doesn't support Pipfile (no pipenv builder).

Given that Makefile doesn't require `make build` upon source code changes removing that option would be a regression.

Side note: This could be implemented in `sam build --watch` via a watchdog using something OS-independent like [watchgod](https://github.com/samuelcolvin/watchgod).

---

## TODO

Default project rendering will use `sam build` and `requirements.txt`. When user opts to use `Makefile` we will use `make` and `Pipfile`.

- [ ] Remove `Pipfile` if Makefile isn't chosen via `hooks`
- [ ] Update `template.yaml` to not use `/build`
- [ ] Remove `.coveragerc` file
- [ ] Update instructions in `README`
- [ ] **Debug why `boto3` and `xray-sdk deps` fail on sam build**
    + [ ] Open up an issue/pr in upstream sam-cli to improve debugging once found

---

**requirements.txt**

```bash
boto3
aws-xray-sdk

```

**`sam build` debug output**

```bash
2018-11-20 11:16:14 Using SAM Template at /Users/lessa/AWS/Projects/Workspace/src/cookiecutter-aws-sam-python/sam-python-app/template.yaml
2018-11-20 11:16:14 Loading variable profile from defaults.
2018-11-20 11:16:14 Loading variable config_file from defaults.
2018-11-20 11:16:14 Loading variable credentials_file from defaults.
2018-11-20 11:16:14 Loading variable data_path from defaults.
2018-11-20 11:16:14 Loading variable profile from defaults.
2018-11-20 11:16:14 Loading variable config_file from defaults.
2018-11-20 11:16:14 Loading variable credentials_file from defaults.
2018-11-20 11:16:14 Loading variable data_path from defaults.
2018-11-20 11:16:14 'build' command is called
2018-11-20 11:16:14 No Parameters detected in the template
2018-11-20 11:16:14 3 resources found in the template
2018-11-20 11:16:14 Found Serverless function with name='FirstFunction' and CodeUri='first_function'
2018-11-20 11:16:14 Building resource 'FirstFunction'
2018-11-20 11:16:14 Loading workflow module 'aws_lambda_builders.workflows'
2018-11-20 11:16:14 Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2018-11-20 11:16:14 Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2018-11-20 11:16:14 Running workflow 'PythonPipBuilder'
2018-11-20 11:16:14 Running PythonPipBuilder:ResolveDependencies
2018-11-20 11:16:30 PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/Users/lessa/.pyenv/versions/3.6.2/envs/work/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 28, in execute
    self.runtime,
  File "/Users/lessa/.pyenv/versions/3.6.2/envs/work/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 120, in build_dependencies
    requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/Users/lessa/.pyenv/versions/3.6.2/envs/work/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 185, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {future==0.17.1(sdist), wrapt==1.10.11(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lessa/.pyenv/versions/3.6.2/envs/work/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 164, in run
    action.execute()
  File "/Users/lessa/.pyenv/versions/3.6.2/envs/work/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 31, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {future==0.17.1(sdist), wrapt==1.10.11(sdist)}
Error: PythonPipBuilder:ResolveDependencies - {future==0.17.1(sdist), wrapt==1.10.11(sdist)}

```

**Comment by sanathkr** [comment]
I am not able to repro this on my machine with this repo. I am using python 3.6.4. 

Edit: I installed Python 3.6.2 - this fails on my machine in this python 3.6.2. I am surprised it failed on just two patch revisions behind

**Comment by sanathkr** [comment]
Also, can you just have `make build` call `sam build` instead? What would be the regression?

**Comment by heitorlessa** [comment]
@sanathkr `make build SERVICE="function"` is only run once and changes to the original source code are replicated to the build folder -- That's what I mean by regression as you'd have to run `sam build` every time you change the file hence the note at the top:

> Given that Makefile doesn't require make build upon source code changes removing that option would be a regression.
> Side note: This could be implemented in sam build --watch via a watchdog using something OS-independent like watchgod.

I found an alternative way and will go forward with the update (sam build within Makefile) that should be pushed tomorrow (crossing 3 different timezones today).

**Comment by heitorlessa** [comment]
cc @sanathkr  as PR is now open and ready to be merged --- If you can have a second look I'd appreciate as I haven't pushed the PR to add integration tests for this boilerplate.

Tested locally with all options and deployed them all but there's always something that can go missing.

**Comment by stevenringo** [comment]
`sam build` has a problem in that it uses the Python environment installed on the host machine. As an example my local machine has Python 3.7 installed, but `sam build` barfs because it expects `3.6` Further you ideally want to have the same version of Python and environment as Lambda for building, which makes using the `lambci` Docker option as per the `Makefile` a really good option.

**Comment by sanathkr** [comment]
@stevenringo Correct, that is what is happening now. Certainly not ideal. We already have a work-in-progress PR to fix this (more context: https://github.com/awslabs/aws-sam-cli/issues/797). Meanwhile you can do `sam build --use-container` which will use lambci container to build automatically. It will choose the right container to build.

Is there anything else that was bugging you with `sam build` that you'd like to get fixed?

PS: I am one of the devs who build `sam build` :)

**Comment by stevenringo** [comment]
Thank you so much @sanathkr. I had no idea about the `--use-container` switch.

**Comment by heitorlessa** [comment]
@stevenringo `make build DOCKER=1` makes use of that so the experience remains the same BUT **will** use `sam build` now ;)

PR pending review is now here and feel free to Chime in: https://github.com/aws-samples/cookiecutter-aws-sam-python/pull/25

@johnt337 ^^ -- I know you've been working on `make invoke` option and I'd love your inputs too as we:

* `make build` will now use `sam build` instead
* `Makefile` becomes no longer experimental and gets added by default (instructions for non-make users are also added)
* Add `event.json` sample at the root directory (i.e. sam local invoke FirstFunction -e event.json)
    - `sam local invoke` now also accepts `--no-event` which may be helpful to the option you were working on

**Comment by heitorlessa** [comment]
Resolving as #31 has been merged
